steps:
- name: maven:3.6-jdk-8-slim
  entrypoint: 'mvn'
  args: ['clean' , 'install']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/weatherapp', '.']
images: ['gcr.io/$PROJECT_ID/weatherapp']